
6. Bonus Features

    Deployment Using Kubernetes

   Create Kubernetes Deployment (deployment.yaml)

   apiVersion: apps/v1

   kind: Deployment

   metadata:

  	name: blog-service

	spec:

  	replicas: 2

  	selector:
    		matchLabels:
      		app: blog-service

  	template:
          metadata:
            labels:
              app: blog-service

    	  spec:
      	   containers:
      		- name: blog-service
        	  image: your-docker-repo/blog-service:latest

           ports:
        	- containerPort: 8080
 



